# Generated by Django 4.0.4 on 2022-05-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': {('cancel_order', 'Can Cancel Order')}},
        ),
    ]
